[directory]
format = "[ $path ]($style)"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "

[git_status]
format = '[$all_status]($style)'

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
