[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
dynamic_padding = true
startup_mode = "Maximized" 

[window.padding]
x = 5
y = 5

[scrolling]
history = 10000
multiplier = 2

[general]

live_config_reload = true
import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

[terminal]

[terminal.shell]
args = ["-l", "-c", "zellij"]
program = "/usr/bin/zsh"
