import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
dynamic_padding = true
startup_mode = "Maximized" 

[window.padding]
x = 3
y = 3

[scrolling]
history = 10000
multiplier = 2
