[font]
size = 16

builtin_box_drawing = true

normal = { family = "Agave Nerd Font Mono", style = "Regular" }
bold = { family = "Agave Nerd Font Mono", style = "Bold" }
italic = { family = "Agave Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Agave Nerd Font Mono", style = "Bold Italic" }
